package com.urlshortener.service;

import com.urlshortener.dto.ShortenRequest;
import com.urlshortener.dto.ShortenResponse;
import com.urlshortener.model.UrlMapping;
import com.urlshortener.repository.UrlMappingRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("UrlService Tests")
class UrlServiceTest {

    @Mock
    private UrlMappingRepository urlMappingRepository;

    @Mock
    private CacheService cacheService;

    @Mock
    private AnalyticsProducer analyticsProducer;

    @InjectMocks
    private UrlService urlService;

    private UUID apiKeyId;

    @BeforeEach
    void setUp() {
        apiKeyId = UUID.randomUUID();
        ReflectionTestUtils.setField(urlService, "baseUrl", "http://localhost");
        ReflectionTestUtils.setField(urlService, "shortCodeLength", 7);
        ReflectionTestUtils.setField(urlService, "defaultTtlDays", 365);
    }

    @Test
    @DisplayName("Should shorten a URL with auto-generated code")
    void shortenUrl_autoGenerated() {
        ShortenRequest request = ShortenRequest.builder()
                .longUrl("https://example.com/very/long/path")
                .build();

        // Mock: save always returns the input entity with an ID assigned
        when(urlMappingRepository.save(any(UrlMapping.class))).thenAnswer(inv -> {
            UrlMapping m = inv.getArgument(0);
            if (m.getId() == null) {
                m.setId(12345L);
            }
            return m;
        });

        ShortenResponse response = urlService.shortenUrl(request, apiKeyId);

        assertNotNull(response);
        assertNotNull(response.getShortUrl());
        assertTrue(response.getShortUrl().startsWith("http://localhost/"));
        assertEquals("https://example.com/very/long/path", response.getLongUrl());
        verify(cacheService).cacheUrl(anyString(), eq("https://example.com/very/long/path"), any());
    }

    @Test
    @DisplayName("Should shorten a URL with custom alias")
    void shortenUrl_customAlias() {
        ShortenRequest request = ShortenRequest.builder()
                .longUrl("https://example.com")
                .customAlias("my-link")
                .build();

        when(urlMappingRepository.existsByShortCode("my-link")).thenReturn(false);
        when(urlMappingRepository.save(any(UrlMapping.class))).thenAnswer(inv -> {
            UrlMapping m = inv.getArgument(0);
            m.setId(1L);
            return m;
        });

        ShortenResponse response = urlService.shortenUrl(request, apiKeyId);

        assertNotNull(response);
        assertEquals("my-link", response.getShortCode());
        assertEquals("http://localhost/my-link", response.getShortUrl());
    }

    @Test
    @DisplayName("Should throw when custom alias already exists")
    void shortenUrl_duplicateAlias() {
        ShortenRequest request = ShortenRequest.builder()
                .longUrl("https://example.com")
                .customAlias("taken")
                .build();

        when(urlMappingRepository.existsByShortCode("taken")).thenReturn(true);

        assertThrows(IllegalArgumentException.class,
                () -> urlService.shortenUrl(request, apiKeyId));
    }

    @Test
    @DisplayName("Should resolve URL from cache")
    void resolveUrl_cacheHit() {
        when(cacheService.getCachedUrl("abc1234")).thenReturn("https://example.com");

        Optional<String> result = urlService.resolveUrl("abc1234");

        assertTrue(result.isPresent());
        assertEquals("https://example.com", result.get());
        verify(urlMappingRepository, never()).findByShortCodeAndIsActiveTrue(any());
    }

    @Test
    @DisplayName("Should resolve URL from DB on cache miss")
    void resolveUrl_cacheMiss_dbHit() {
        when(cacheService.getCachedUrl("abc1234")).thenReturn(null);
        when(urlMappingRepository.findByShortCodeAndIsActiveTrue("abc1234"))
                .thenReturn(Optional.of(UrlMapping.builder()
                        .shortCode("abc1234")
                        .longUrl("https://example.com")
                        .isActive(true)
                        .build()));

        Optional<String> result = urlService.resolveUrl("abc1234");

        assertTrue(result.isPresent());
        assertEquals("https://example.com", result.get());
        // Should populate cache
        verify(cacheService).cacheUrl("abc1234", "https://example.com");
    }

    @Test
    @DisplayName("Should return empty for non-existent short code")
    void resolveUrl_notFound() {
        when(cacheService.getCachedUrl("nope123")).thenReturn(null);
        when(urlMappingRepository.findByShortCodeAndIsActiveTrue("nope123"))
                .thenReturn(Optional.empty());

        Optional<String> result = urlService.resolveUrl("nope123");

        assertTrue(result.isEmpty());
    }

    @Test
    @DisplayName("Should return empty for expired URL")
    void resolveUrl_expired() {
        when(cacheService.getCachedUrl("exp1234")).thenReturn(null);
        when(urlMappingRepository.findByShortCodeAndIsActiveTrue("exp1234"))
                .thenReturn(Optional.of(UrlMapping.builder()
                        .shortCode("exp1234")
                        .longUrl("https://expired.com")
                        .isActive(true)
                        .expiresAt(Instant.now().minusSeconds(3600)) // expired 1 hour ago
                        .build()));

        Optional<String> result = urlService.resolveUrl("exp1234");

        assertTrue(result.isEmpty());
    }

    @Test
    @DisplayName("Should record click via Kafka producer")
    void recordClick() {
        urlService.recordClick("abc1234", "127.0.0.1", "Mozilla/5.0", "https://google.com");

        verify(analyticsProducer).publishClickEvent("abc1234", "127.0.0.1", "Mozilla/5.0", "https://google.com");
    }

    @Test
    @DisplayName("Should deactivate URL and evict cache")
    void deactivateUrl() {
        UrlMapping mapping = UrlMapping.builder()
                .shortCode("abc1234")
                .longUrl("https://example.com")
                .isActive(true)
                .apiKeyId(apiKeyId)
                .build();

        when(urlMappingRepository.findByShortCodeAndIsActiveTrue("abc1234"))
                .thenReturn(Optional.of(mapping));
        when(urlMappingRepository.save(any())).thenReturn(mapping);

        boolean result = urlService.deactivateUrl("abc1234", apiKeyId);

        assertTrue(result);
        assertFalse(mapping.getIsActive());
        verify(cacheService).evictUrl("abc1234");
    }

    @Test
    @DisplayName("Should throw when deactivating URL owned by another key")
    void deactivateUrl_wrongOwner() {
        UUID otherKeyId = UUID.randomUUID();
        UrlMapping mapping = UrlMapping.builder()
                .shortCode("abc1234")
                .apiKeyId(otherKeyId)
                .isActive(true)
                .build();

        when(urlMappingRepository.findByShortCodeAndIsActiveTrue("abc1234"))
                .thenReturn(Optional.of(mapping));

        assertThrows(SecurityException.class,
                () -> urlService.deactivateUrl("abc1234", apiKeyId));
    }
}
